# Generated by Django 2.2.5 on 2019-10-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=32, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clothpicture',
            name='clothing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.Customer'),
        ),
    ]
