# Generated by Django 2.2.5 on 2019-10-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0002_auto_20191006_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothpicture',
            name='color',
            field=models.IntegerField(choices=[(1, 'Red'), (2, 'Black'), (3, 'Blue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
